### PR TITLE
Issue 8 font glyph assets

### LINKED ISSUE #8: Add glyph and assets for Navigation Pane
Add glyph in font file and respective assets for the navigation pane in Calculator.

### PR DESCRIPTION
**Pull request by theEhlien**
Created font assets for navigation pane and replaced glyph code to represent those changes. Closes #8

### CODE REVIEW

**Comment by Jared-Gibson** [comment]
I noticed that for the size 64 you removed a contrast-white and only added a contrast-black; is this intentional or did you forget to add a new contrast-white and remove an old contrast black?

**Comment by theEhlien** [comment]
@Jared-Gibson I looked into it. Everything looks like it is correct. The reason two files weren't changed in the same way as the rest is due to the naming scheme. I named the other files incorrectly and those two correctly. All the files should be correct now though.

**Review by Jared-Gibson — APPROVED** [review]
Did a test of the branch and saw that the integral symbol was present. Everything looks good; approving the pull request.

**Comment by Nicolo7** [comment]
Also ran a test and everything seems to be in place. I couldn't find any problems or potential bugs either.

**Comment by smalls4894** [comment]
Tests are bug free, fix for symbolic glyph well documented, symbolic assets for navigation pane work great

**Pull request merged**
